ALTER TABLE [dbo].[DiscountGroups]
    ADD CONSTRAINT [PK_DiscountGroups] PRIMARY KEY CLUSTERED ([DiscountGroupId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

